version: '3.7'
services:
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - 80
    depends_on:
      - php-fpm
    networks:
      default:
      buoy:
        aliases:
          - guarded-cookie-php

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app
      - ./composer:/.composer
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - GUARDED_COOKIE_DOMAIN
      - GUARDED_COOKIE_HASH_KEY
      - GUARDED_COOKIE_ENCRYPTION_KEY
    ports:
      - 9000

networks:
  buoy:
    external:
      name: buoy
